module.exports = {
  content: [
    './templates/**/*.html',
    './static/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        'jetbrains': ['"JetBrains Mono"', 'monospace'], // Add JetBrains Mono font
      },
      colors: {
        'red': '#FF0000',
        'green': '#00FF00',
        'blue': '#0000FF',
        'yellow': '#FFFF00',
        'purple': '#800080',
        'orange': '#FFA500',
        'pink': '#FFC0CB',
        'cyan': '#00FFFF',
        'lime': '#00FF00',
        'indigo': '#4B0082',
        'violet': '#EE82EE',
        'brown': '#A52A2A',
        'grey': '#808080',
        'black': '#000000',
        'white': '#FFFFFF',
        },
    },

  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        cache: {
          "primary": "#fcc55e",
          "secondary": "#0f766e",
          "accent": "#57534e",
          "neutral": "#fbcfe8",
          "base-100": "#ffffff",
         // "primary-content": "#75fb4c", //this is for sustain
          "info": "#38bdf8",
          "success": "#4ade80",
          "warning": "#f97316",
          "error": "#dc2626",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
}
